### ISSUE TITLE
ryo-modal and emacsclient

### ISSUE THREAD

**Issue by thorstengrothe** [Kungsgeten/ryo-modal#12]
I'm switching to emacsclient to reduce my startup time and have a issue with ryo-modal. When switching ryo-modal on or off I got this error:
`
Error in post-command-hook (ryo-modal--cursor-color-update): (wrong-type-argument stringp unspecified)`

I have no clue what to do...

Regards
Thorsten

**Comment by Kungsgeten** [comment]
Hmm, if you type `C-h v ryo-modal-default-cursor-color` you should get information about the `ryo-modal-default-cursor-color` variable. What value does it have?

`ryo` has a function in the `post-command-hook` which updates the cursor color. It seems something is wrong there. You could also use `M-x toggle-debug-on-error` and try again, which may yield more information.

**Comment by thorstengrothe** [comment]
Ahh, there's one problem, `ryo-modal-default-cursor-color` without emacsclient says:  `"#51afef"`; with `emacsclient/daemon` it says `unspecified`. Second thing is that ryo-modal does not change color and shape in command/insert mode with `emacsclient/daemon`. 

`toogle-debug-on-error` says this:

 ```
(wrong-type-argument stringp unspecified)
  modify-frame-parameters(#<frame emacs@manjothor 0x85e4298> ((cursor-color . unspecified)))
  set-cursor-color(unspecified)
  ryo-modal-mode(toggle)
  funcall-interactively(ryo-modal-mode toggle)
  call-interactively(ryo-modal-mode nil nil)
  command-execute(ryo-modal-mode)
```

I got a similar issue with my theme loading in client mode and use this code snippet for this

```
(if (daemonp)
    (add-hook 'after-make-frame-functions
        (lambda (frame)
            (with-selected-frame frame
		... 
                )))  
    ;; no daemon
	)
```

But I have no idea how to realize this with ryo-modal

Thorsten

**Comment by Kungsgeten** [comment]
You could try adding `(setq ryo-modal-default-cursor-color "#51afef")` to your init-file. The downside is that you'll probably want to change this if you switch color theme.

**Comment by thorstengrothe** [comment]
This seems to work, the error is gone away, I will test a few days and see if everything works. Thank you.
