### ISSUE TITLE
Can something like Kakoune be implemented with this

### ISSUE THREAD

**Issue by nightscape** [Kungsgeten/ryo-modal#15]
Hi @Kungsgeten,

I just stumbled upon [Kakoune](
http://kakoune.org/) and I'm quite amazed that it beats the VIM keybindings in terms of speed (required number of keypresses) and simplicity.
The main difference is that Kakoune uses an object then verb grammar whereas VIM uses verb then motion.

Now I'm wondering if implementing Kakoune-style keybindings with Ryo would be rather straight-forward or be completely opposite to the current model.
I'm not (yet) an Elisp programmer myself, so I could only tackle it in the first case...

**Comment by Kungsgeten** [comment]
I haven't used Kakoune, and I'm not familiar with it. The main feature seems to have multiple selections, which may be hard to do in Emacs (don't know how good `multiple-cursors` is in this regard).

If the idea is to first select som text, and then do something with the selected text, then `ryo` + `selected` should probably work fine.

**Comment by jmorag** [comment]
Yes, it can! See my package [kakoune.el](https://github.com/jmorag/kakoune.el)
