### ISSUE TITLE
[Question] Making repeat work similar to ryo-modal-repeat

### ISSUE THREAD

**Issue by sriramkswamy** [Kungsgeten/ryo-modal#19]
After the recent update, I noticed that the `ryo-modal-repeat` command is deprecated. However, I was wondering if there is a way to replicate its functionality. Consider the following scenario -

- `D` key in `ryo-modal-mode` is mapped to `C-k`
- `j` key in `ryo-modal-mode` is mapped to `C-n` with `:norepeat t`
- Previously, with `ryo-modal-repeat` if press `D` and then `j`, calling `ryo-modal-repeat` would perform the action mapped to `D` and not `j`
- Currently, the example mentioned above when used with `repeat` repeats the action `j` and not `D`

Is there any way to restore the old functionality? And if this is not in the road map, the current README suggests that this is true.

Also, thank you for the new update! Multiple cursors works seamlessly now after mapping the `mc/*` commands using `define-key`.

**Comment by Kungsgeten** [comment]
Hmm, perhaps there's still a need for the repeat feature after all! :) I just thought it wouldn't be needed, because the standard `repeat` command should work. It is true however that now it isn't possible to use `:norepeat`, which might be a good feature. I'll look into it!

**Comment by Kungsgeten** [comment]
It seems like I have misunderstood the purpose of the Emacs `repeat` command. I'll try to add `ryo-modal-repeat` once again :)

**Comment by Kungsgeten** [comment]
I've re-added `ryo-modal-repeat` and I think it'll work with the new system. Also it is now possible to bind `ryo-modal-repeat` using `ryo-bind-key(s)` if you want to :)
