### ISSUE TITLE
Key repeat delay while ryo-modal-mode is active

### ISSUE THREAD

**Issue by jhenahan** [Kungsgeten/ryo-modal#23]
I’ve noticed that key repeat is either nonfunctional or extremely delayed while the mode is active. To reproduce, enable the mode, then hold down any key without a ryo binding (say, an arrow). In my experience, either the key won’t repeat at all, or it will repeat with a significant delay between each repetition. Disabling the mode makes the problem disappear. I’ll dig through the source tomorrow to see if I can figure out where it happens, unless you beat me to it.

**Comment by Kungsgeten** [comment]
It works fine in my Emacs. I haven't tried it with a fresh `emacs -q` though, have you?

**Comment by jhenahan** [comment]
Looks like you're right. I disabled all minor modes, then turned ryo back on and key repeat seems fine. Guess I'll have to look around elsewhere. Appreciate the sanity check!
