### ISSUE TITLE
globally enabling ryo-modal mode?

### ISSUE THREAD

**Issue by saheratarch** [Kungsgeten/ryo-modal#26]

**Comment by Kungsgeten** [comment]
There's no built-in way to do it. The reason is that I think there's a lot of buffers where you don't want ryo to be active. Here's what I'd do if you want to activate ryo almost everywhere:

```
(add-hook 'text-mode-hook #'ryo-modal-mode)
(add-hook 'prog-mode-hook #'ryo-modal-mode)
```

**Comment by saheratarch** [comment]
Sorry if the question was too trivial

**Comment by Kungsgeten** [comment]
No problem at all! I'm glad you enjoy the package :)
