### ISSUE TITLE
universal argument does not multiply

### ISSUE THREAD

**Issue by kahironimashte** [Kungsgeten/ryo-modal#32]
Same as here: [https://github.com/mrkkrp/modalka/issues/24](https://github.com/mrkkrp/modalka/issues/24)

The hack in the comments works for ryo too: 

`(define-key universal-argument-map (kbd "u") 'universal-argument-more)`

**Comment by Kungsgeten** [comment]
This worked for me in `ryo-modall-mode`:

```
(defun universal-argument-or-more ()
  "Call `universal-argument' or `universal-argument-more',
if there's already a `current-prefix-arg'."
  (interactive)
  (call-interactively
   (if current-prefix-arg
       #'universal-argument-more
     #'universal-argument)))

(ryo-modal-key "u" #'universal-argument-or-more)
```
