### ISSUE TITLE
ryo-modal-repeat with any previous key?

### ISSUE THREAD

**Issue by juhanoi** [Kungsgeten/ryo-modal#35]
hi

is there some (easy) way to bind ryo-modal-repeat for any previous key?

for example, i would like to make a binding so that,  if you pressed "d k k k", then it would do the same as typing "d k", "d k", "d k". 

the example config has ryo-modal-repeat bound to "," which is fine for some i suppose (vim does something like that, right?), but now i have to type "d k , ," which i find confusing

im not really good with elisp, not sure how to do this

**Comment by Kungsgeten** [comment]
Hi! No, there's no such functionality built into `ryo-modal`, unless you're using a `hydra`. I haven't used it myself but there's a package named `smartrep` which might help: https://github.com/myuhe/smartrep.el

**Comment by Kungsgeten** [comment]
There's also this post: https://oremacs.com/2015/01/14/repeatable-commands/

**Comment by juhanoi** [comment]
alright 
thanks for advice
