### ISSUE TITLE
Binding gets unbound once opening a file

### ISSUE THREAD

**Issue by semilin** [Kungsgeten/ryo-modal#36]
This is a really weird issue I've never had before. I'm using emacs-dashboard, and toggling ryo with ESC works just fine in that buffer. However, as soon as I open a file, pressing ESC will result in ESC acting as a meta key.

In addition, M-x gets unbound.

**Comment by Kungsgeten** [comment]
Hmm, that sounds strange indeed! I'm not 100% sure but I think the ESC-key is special in Emacs somehow. Does it work if you use a different keybinding? What does your config look like, where you bind ESC to ryo-modal-mode?

**Comment by semilin** [comment]
Ah, turns out that I was simply binding escape incorrectly. Although describe-key writes it as ESC, the proper code is <escape>.
