### ISSUE TITLE
Unable to bind Hydra with Prefix

### ISSUE THREAD

**Issue by EPonyA** [Kungsgeten/ryo-modal#38]
Howdy! I've been struggling to set up a hydra. Based on the README, I wrote this in my init file:

```
(use-package ryo-modal
  ...
  :config
  (ryo-modal-key
	"SPC g" :hydra
	'(hydra-buffer (:color red)
						"Buffer Hydra"
						("t" split-window-below "Split Vertically")
						...
						("<BACKSPACE>" nil "Cancel" :color blue)
						))
  ...
)
```
However, when I evaluate my buffer and press SPC and g, Emacs prints `SPC g is undefined`. I can't see any meaningful difference between what I've written, and what the README advises, so I'm unsure whether I've missed something or whether the README is incorrect.

I thought maybe the parentheses could've been wrong, so I tried it like this:
```
  (ryo-modal-keys
	("SPC g" :hydra
	 '(hydra-buffer (:color red)
						...
						 )))
```
This produces the same result.

The following snippet returns no errors, and seems to behave correctly, but I want SPC as a prefix to g.
```
 (ryo-modal-keys
  ("g" :hydra
	'(hydra-buffer (:color red)
						"Buffer Hydra"
						("t" split-window-below "Split Vertically")
						...
						("<BACKSPACE>" nil "Cancel" :color blue)
						)))
```

I tried writing the recursive keybindings in the same way I've gotten non-hydra commands to work in RYO-mode:
```
  ;; Buffer management.
  (ryo-modal-keys
	("SPC" (
			  ("g" :hydra
				'(hydra-buffer (:color red)
									"Buffer Hydra"
									("t" split-window-below "Split Vertically")
									...
									("<BACKSPACE>" nil "Cancel" :color blue)
									)))))
```

That gives me this error:
```
Error (use-package): ryo-modal/:config: Wrong type argument: plistp, ("Buffer Hydra" ("t" split-window-below "Split Vertically") ("n" split-window-right "Split Rightward") ("T" buf-move-down "Focus Down") ("C" buf-move-up "Focus Up") ("N" buf-move-right "Focus Right") ("H" buf-move-left "Focus Left") ("e" ace-delete-window "Kill") ("w" ace-delete-other-windows "Kill All Except") ("p" switch-to-buffer "Switch") ("<BACKSPACE>" nil "Cancel" :color blue))
```

At this point I have no clue how to bind a hydra to SPC + g.

**Comment by Kungsgeten** [comment]
Hi! Sorry for the late response to this. Your first example works for me, like this:

```
(ryo-modal-key
 "SPC g" :hydra
 '(hydra-buffer (:color red)
		"Buffer Hydra"
		("t" split-window-below "Split Vertically")
		("<BACKSPACE>" nil "Cancel" :color blue)
		))
```

Could it be the case that you've already bound `SPC` to something else in `ryo-modal-mode`? For instance if I do this:

```
(ryo-modal-key "SPC" #'next-line)

(ryo-modal-key
 "SPC g" :hydra
 '(hydra-buffer (:color red)
		"Buffer Hydra"
		("t" split-window-below "Split Vertically")
		("<BACKSPACE>" nil "Cancel" :color blue)
		))
```

I get the error `"Key sequence SPC g starts with non-prefix key SPC"`.
