### ISSUE TITLE
Error from which-key

### ISSUE THREAD

**Issue by xircon** [Kungsgeten/ryo-modal#48]
I do not know if this is an ryo problem, but am going around in circles trying to fix.  Which-key has updated and:
```
2021-06-21: Add support for menu-item bindings
which-key will now detect and compute the result of menu-item bindings. As a consequence of reworking the internals, which-key-enable-extended-define-key is now obsolete (the associated behavior is supported by default).
```
I get the error:
```
vError (use-package): init-my-ryo/:catch: Symbol’s value as variable is void: which-key-enable-extended-define-key Disable showing Disable logging
```
Init-my-ryo is just all of my settings in one file.  There is no reference to which-key in this file, any help gratefully accepted :smiley: 

Think the error is:
```
 (cond
   ((listp target)
    (when (and (require 'which-key nil t)
               which-key-enable-extended-define-key
               (plist-get args :name))
```
Around line 140 (ish).  Will disable which-key for now - ryo is more important!!

**Comment by Kungsgeten** [comment]
Sorry! Didn't see your PR before I changed it myself :) Hopefully this should work.

**Comment by xircon** [comment]
Thanks just downloaded from melpa.
