### ISSUE TITLE
Exclude modes?

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/ryo-modal#5]
Hi,

I'm trying to replace my modalka config because I find the extensions you've added on top if it really excellent. One thing I haven't found is auto-exclusion from certain modes - like the modalka-excluded-modes. Is there a way to achieve this? i.e. whenever I switch to org-agenda ryo is disabled (if it wasn't already).

Thank you!

**Comment by Kungsgeten** [comment]
Hi! Not at the moment, no. I'm not sure how that works in modalka, but I'll look into it. I personally do it the other way around: I add `ryo-modal-mode` to the major-mode hooks where I want it active.

**Comment by Kungsgeten** [comment]
Modalka has a globalized minor mode, and ryo does not. You'll have to actively activate ryo in some way (like in a hook, or by pressing a key). How do you activate ryo at the moment, and how would you like it to work?

Currently ryo  is enabled/disabled per buffer basis, so if you switch to org-agenda ryo should be off, and then when you switch back it should be on/off depending on the state in which you left that buffer.

**Comment by rsuhada** [comment]
Sorry I was on sabbatical at that time and didn't get back to ryo until now.
Understood - I switched to explicitely activating ryo (essentially everywhere :)) and it seems to work fine.

Thank you!

PS: same for https://github.com/Kungsgeten/ryo-modal/issues/6 (both issues can be closed)
