### ISSUE TITLE
Error when using :then or :first 

### ISSUE THREAD

**Issue by kahironimashte** [Kungsgeten/ryo-modal#52]
I would like to store the current location before jumping to a bookmark:

`("b" bookmark-jump :first '(org-mark-ring-push))`

But I get an error: `apply: Wrong number of arguments: #<subr quote>, 0`

The simpler version `("b" bookmark-jump)` works perfectly. What am I doing wrong?

**Comment by Kungsgeten** [comment]
Not sure. Try to remove the quote. I'm not at my computer at the moment, but may be able to debug later.

**Comment by kahironimashte** [comment]
Excellent! `("b" bookmark-jump :first (org-mark-ring-push))` works. Thanks for the quick reply!

The `:first` and `:then` functionality is very handy. From the readme I thought that we are supposed to use quoted lists. Are quotes still required in general?

**Comment by Kungsgeten** [comment]
I think quoting is required when using ryo-modal-key, but not when using ryo-modal-keys
