### ISSUE TITLE
Make ryo-mode on per default

### ISSUE THREAD

**Issue by thorstengrothe** [Kungsgeten/ryo-modal#7]
Hi,

I used xah fly keys before but it's too much for me, ryo is simpler to configure and I like it very much. One thing would be nice. Say we switch to a new buffer with ivy-switch-buffer, then ryo mode is not enabled. It would be nice if one can enable it for every new buffer or file per default. 
The same is for opening a new file, ryo should be on per default, I think!

Is that possible?

Regards
Thorsten

**Comment by Kungsgeten** [comment]
Hi! Glad you like ryo! A thing you could do is to add `ryo-modal-mode` to the hooks of the modes where you want ryo to be active by default. If you want that for most text editing major-modes, you could add the following to your init-file:

```
(add-hook 'text-mode-hook #'ryo-modal-mode)
(add-hook 'prog-mode-hook #'ryo-modal-mode)
```

**Comment by thorstengrothe** [comment]
Yes that works, simple and effective, thank you!

Regards
Thosren
